# -*- mode: yaml -*-
# vim: set filetype=yaml tabstop=4 shiftwidth=4 autoindent smartindent:
site_name: "Tim's Best Practices and Notes"
site_url: https://timwarnock.github.io/best-practices-and-notes/
site_description: Best Practices and Notes that I found useful
site_author: Timothy Warnock

repo_url: https://github.com/timwarnock/best-practices-and-notes
repo_name: timwarnock/best-practices-and-notes
edit_uri: ""

theme:
    name: material
    palette:
        primary: black
    custom_dir: mkdocs-overrides
    logo: images/logo.png
    favicon: images/favicon.png

nav:
    - Best Practices:
        - Conventional Commits: conventional-commits.md
        - Good Architecture: good-architecture.md
        - Good Code: good-code.md
        - Good Teams: good-teams.md
    - Opinions:
        - End of Agile: agile.md

markdown_extensions:
  - admonition
  - toc:
      permalink: True
